// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Booking struct {
	ID   string `json:"id"`
	From string `json:"from"`
	To   string `json:"to"`
	User *User  `json:"user"`
}

type Cab struct {
	ID       string `json:"id"`
	Location string `json:"location"`
}

type NewBooking struct {
	From string `json:"from"`
	To   string `json:"to"`
}

type NewCab struct {
	Location string `json:"location"`
}

type NewUser struct {
	Name string `json:"name"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
